Move CI to GitHub Actions, appease clippy
Remove feature clap/lints; no longer supported:
```
error[E0557]: feature has been removed
   -->
/Users/tamird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-2.33.4/src/lib.rs:536:40
    |
536 | #![cfg_attr(feature = "lints", feature(plugin))]
    |                                        ^^^^^^ feature has been
removed
    |
    = note: plugins are no longer supported
```

Bump MSRV as forced by dependencies.